export const QUOTES: string[] = [
  "THE IRON NEVER LIES.",
  "PAIN IS WEAKNESS LEAVING THE BODY.",
  "YOU DON'T FIND WILLPOWER. YOU BUILD IT.",
  "DISCIPLINE OUTLASTS MOTIVATION.",
  "EARNED. NOT GIVEN.",
  "BLOOD, SWEAT, RESPECT.",
  "THE WOLF ON THE HILL IS NOT AS HUNGRY AS THE WOLF CLIMBING IT.",
  "DO NOT PRAY FOR AN EASY LIFE. PRAY FOR THE STRENGTH TO ENDURE A DIFFICULT ONE.",
  "SUFFER THE PAIN OF DISCIPLINE OR SUFFER THE PAIN OF REGRET.",
  "YOUR BODY KEEPS AN ACCURATE JOURNAL EVEN IF YOU DON'T.",
  "WE ARE WHAT WE REPEATEDLY DO. EXCELLENCE IS NOT AN ACT, BUT A HABIT.",
  "IF IT DOESN'T CHALLENGE YOU, IT DOESN'T CHANGE YOU.",
  "THE ONLY BAD WORKOUT IS THE ONE THAT DIDN'T HAPPEN.",
  "STRENGTH DOES NOT COME FROM PHYSICAL CAPACITY. IT COMES FROM AN INDOMITABLE WILL.",
  "FALL SEVEN TIMES. STAND UP EIGHT.",
  "YOU HAVE TO FIGHT THROUGH SOME BAD DAYS TO EARN THE BEST DAYS OF YOUR LIFE.",
  "SUCCESS IS NOT OWNED. IT IS LEASED. AND RENT IS DUE EVERY DAY.",
  "MAKE YOURSELF HARDER TO KILL.",
  "THE MAN WHO MOVES A MOUNTAIN BEGINS BY CARRYING AWAY SMALL STONES.",
  "EVERY CHAMPION WAS ONCE A CONTENDER WHO REFUSED TO GIVE UP.",
  "I DON'T COUNT MY SIT-UPS. I ONLY START COUNTING WHEN IT STARTS HURTING.",
  "HARD WORK BEATS TALENT WHEN TALENT DOESN'T WORK HARD.",
  "PAIN IS TEMPORARY. QUITTING LASTS FOREVER.",
  "NO SHORTCUTS. NO EXCUSES. NO MERCY.",
  "BECOME WHO YOU WERE MEANT TO BE.",
  "YOUR FUTURE SELF IS WATCHING YOU RIGHT NOW THROUGH MEMORIES.",
  "THE CLOCK IS TICKING. ARE YOU BECOMING THE PERSON YOU WANT TO BE?",
  "CHAMPIONS AREN'T MADE IN GYMS. THEY ARE MADE FROM SOMETHING DEEP INSIDE.",
  "THE BODY ACHIEVES WHAT THE MIND BELIEVES.",
  "NOTHING WILL WORK UNLESS YOU DO.",
  "TRAIN INSANE OR REMAIN THE SAME.",
  "DEAD LAST FINISH IS GREATER THAN DID NOT FINISH, WHICH TRUMPS DID NOT START.",
  "WAKE UP WITH DETERMINATION. GO TO BED WITH SATISFACTION.",
  "FIRST, MASTER THE FUNDAMENTALS.",
  "TODAY I WILL DO WHAT OTHERS WON'T. TOMORROW I'LL DO WHAT OTHERS CAN'T.",
  "WARRIORS ARE MADE IN THE MOMENTS THEY WANT TO QUIT BUT DON'T.",
  "IRON SHARPENS IRON.",
  "THE CAVE YOU FEAR TO ENTER HOLDS THE TREASURE YOU SEEK.",
  "MOST PEOPLE GIVE UP JUST WHEN THEY'RE ABOUT TO ACHIEVE SUCCESS.",
  "YOU WERE GIVEN THIS LIFE BECAUSE YOU ARE STRONG ENOUGH TO LIVE IT.",
  "GET COMFORTABLE BEING UNCOMFORTABLE.",
  "SWEAT IS JUST FAT CRYING.",
  "SHUT UP AND SQUAT.",
  "YOU ARE YOUR ONLY COMPETITION.",
  "THE BAR DOESN'T CARE ABOUT YOUR FEELINGS.",
  "ATTACK EACH DAY WITH AN ENTHUSIASM UNKNOWN TO MANKIND.",
  "NO ZERO DAYS.",
  "OUTWORK YOUR EXCUSES.",
  "LIMITS ARE SELF-IMPOSED.",
  "THE GRIND DOESN'T STOP.",
  "HEAVY IS THE HEAD THAT NEVER TRAINED THE NECK.",
  "ONE MORE REP. ALWAYS ONE MORE REP.",
  "YOUR GENETICS LOADED THE GUN. YOUR LIFESTYLE PULLED THE TRIGGER.",
  "BE UNGOVERNABLE.",
  "STAY HARD.",
  "IT PAYS TO BE A WINNER.",
  "EMBRACE THE SUCK.",
  "THE OBSTACLE IS THE WAY.",
  "ADAPT, OVERCOME, DOMINATE.",
  "FORGED UNDER PRESSURE.",
  "BUILT, NOT BOUGHT.",
  "MIND OVER MUSCLE.",
  "NO DAYS OFF FROM BEING DANGEROUS.",
  "THOSE WHO HUSTLE BY DAY SLEEP BETTER BY NIGHT.",
  "AMBITION IS THE FIRST STEP TOWARD SUCCESS. THE SECOND STEP IS ACTION.",
  "CONSISTENCY IS THE TRUE FOUNDATION OF TRUST.",
  "WHEN YOUR LEGS GIVE OUT, TRAIN ON YOUR KNEES.",
  "YOU WERE BORN TO WIN, BUT TO BE A WINNER YOU MUST PLAN TO WIN, PREPARE TO WIN.",
  "THE LAST 3 REPS ARE WHERE THE CHAMPION IS BUILT.",
  "PRESSURE MAKES DIAMONDS.",
  "BLEED NOW OR BLEED LATER.",
  "IF YOU CAN'T OUTPLAY THEM, OUTWORK THEM.",
  "THE DIFFERENCE BETWEEN ORDINARY AND EXTRAORDINARY IS THAT LITTLE EXTRA.",
  "DO IT NOW. SOMETIMES 'LATER' BECOMES 'NEVER'.",
  "FEAR IS A LIAR.",
  "PROVE THEM WRONG.",
  "DEFINE YOURSELF BY YOUR ACTIONS, NOT YOUR INTENTIONS.",
  "ONCE YOU LEARN TO QUIT, IT BECOMES A HABIT.",
  "THE HARDER THE BATTLE, THE SWEETER THE VICTORY.",
  "STEEL YOUR MIND. HARDEN YOUR BODY.",
  "DISCIPLINE IS DOING WHAT NEEDS TO BE DONE EVEN WHEN YOU DON'T WANT TO.",
  "SHOW UP EVERY SINGLE DAY. NO MATTER WHAT.",
  "YOUR ONLY LIMIT IS THE ONE YOU SET YOURSELF.",
  "BE RELENTLESS.",
  "FIGHT FOR EVERY INCH.",
  "LEAVE NOTHING IN THE TANK.",
  "YOUR SACRIFICE TODAY IS YOUR STRENGTH TOMORROW.",
  "NEVER STOP. NEVER SETTLE.",
]

/**
 * Returns a consistent quote for the current hour + day of month.
 * Same call within the same hour always returns the same quote.
 */
export function getQuoteOfHour(): string {
  const now = new Date()
  const index = (now.getHours() + now.getDate() * 24) % QUOTES.length
  return QUOTES[index]
}

/**
 * Returns a quote by absolute index (wraps around).
 */
export function getQuoteByIndex(n: number): string {
  return QUOTES[((n % QUOTES.length) + QUOTES.length) % QUOTES.length]
}

/**
 * Returns a pseudo-random quote seeded by the current minute+second.
 * Stays stable within the same second.
 */
export function getRandomQuote(): string {
  const now = new Date()
  const seed = now.getMinutes() * 60 + now.getSeconds()
  return QUOTES[seed % QUOTES.length]
}
